version: '3.5'
services:

    app:
        build:
            context: src/
            dockerfile: Dockerfile
        environment:
            - db_server=mysql
            - db_pass=p455w0rd
            - db_user=root
        ports:
            - "5000:5000"
        depends_on:
            - mysql

    mysql:
        image: mysql:latest 
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: p455w0rd
            MYSQL_DATABASE: ic-test
        volumes:
            - "./src/schema.sql:/docker-entrypoint-initdb.d/1.sql"


